version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: dockerize -wait tcp://elasticsearch:9200 -timeout 100s -wait http://keycloak:8080 -timeout 100s npm run start:prod
    container_name: micro-api-app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - APP_ENV=prod
      - APP_URL=http://localhost:3000
      - SESSION_SECRET_KEY=fullcycle.com.br
      - ELASTIC_SEARCH_HOST=http://elasticsearch:9200
      - ELASTIC_SEARCH_REQUEST_TIMEOUT=30000
      - ELASTIC_SEARCH_PING_TIMEOUT=3000
      - REDIS_URI=redis://redis:6379/2
      - KEYCLOAK_JSON={"realm":"discord","auth-server-url":"http://keycloak:8080/auth","ssl-required":"external","resource":"nest","verify-token-audience":true,"credentials":{"secret":"69c83a02-6184-4f51-ba5c-e27da4b5ad0b"},"use-resource-role-mappings":true,"confidential-port":0,"policy-enforcer":{}}

    ports:
      - 3000:3000
    depends_on: 
      - elasticsearch
      - keycloak
      - redis
   
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    
  redis:
    image: redis:alpine
    container_name: test-nestjs-api-rest-redis

  keycloak:
    image: wesleywillians/keycloak:latest
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=realm.json
    ports:
      - "8080:8080"